SLSA3 Build
k3s-io/klipper-lb pull request #72
Opened 2024-09-27 16:33 UTC by rafaelbreno

2024-10-10 22:24 UTC, brooksn requested changes

2024-10-10 22:24 UTC, brooksn commented on .github/workflows/release.yml
> +          secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials password | DOCKER_PASSWORD ;
```suggestion
```

2024-10-10 22:24 UTC, brooksn commented on .github/workflows/release.yml
> +        public-password: ${{ env.DOCKER_PASSWORD }}
```suggestion
        platforms: linux/amd64,linux/arm64,linux/arm
        push-to-public: false
```

2024-10-10 22:24 UTC, brooksn commented on Makefile
> +
```suggestion
```

2024-10-10 22:24 UTC, brooksn commented on Makefile
> +BUILDDATE ?= $(date +%Y%m%d)
```suggestion
BUILDDATE ?= $(shell date +%Y%m%d)
```

2024-10-10 22:24 UTC, brooksn commented on Makefile
> +		--tag $(IMAGE)-$(ARCH) \
```suggestion
```

2024-10-11 17:59 UTC, rafaelbreno commented on Makefile
> +		--tag $(IMAGE)-$(ARCH) \
Done

2024-10-11 17:59 UTC, rafaelbreno commented on Makefile
> +BUILDDATE ?= $(date +%Y%m%d)
Done

2024-10-11 17:59 UTC, rafaelbreno commented on Makefile
> +
Done

2024-10-11 17:59 UTC, rafaelbreno commented on .github/workflows/release.yml
> +        public-password: ${{ env.DOCKER_PASSWORD }}
Done

2024-10-11 17:59 UTC, rafaelbreno commented on .github/workflows/release.yml
> +          secret/data/github/repo/${{ github.repository }}/dockerhub/${{ github.repository_owner }}/credentials password | DOCKER_PASSWORD ;
Done

2024-10-11 18:04 UTC, brooksn approved these changes

2024-10-11 18:39 UTC, closed without merging